# API Gateway Configuration
server:
  port: 8989
  shutdown: graceful

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins:
            - "http://localhost:3000"
            - "http://localhost:80"
            - "http://localhost"
            - "http://frontend"
            allowed-methods: "*"
            allowed-headers: "Authorization,Content-Type,Accept,Origin,X-Requested-With"
            allow-credentials: false
      routes:
        - id: catalog-service
          uri: ${CATALOG_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/catalog/**
          filters:
            - RewritePath=/catalog/?(?<segment>.*), /${segment}
        - id: orders-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/orders/**
          filters:
            - RewritePath=/orders/?(?<segment>.*), /${segment}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST
  mvc:
    problemdetails:
      enabled: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0

# Swagger Configuration
springdoc:
  swagger-ui:
    use-root-path: true
  # urls:
  #   - name: catalog
  #     url: /v3/api-docs/catalog
  #   - name: orders
  #     url: /v3/api-docs/orders