# Default configuration for all microservices
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Common logging configuration
logging:
  level:
    root: INFO
    com.kiin: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
