# Development Environment Configuration
spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
    h2:
        console:
            enabled: true

# Logging Configuration for Development
logging:
    level:
        root: INFO
        com.kiin: DEBUG
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Actuator Configuration for Development
management:
    tracing:
        enabled: true
        sampling:
            probability: 1.0
