# Default configuration for all microservices
server:
  shutdown: graceful

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

# Common Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

# Common Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: ${MANAGEMENT_TRACING_ENABLED:true}
  otlp:
    tracing:
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://tempo:4317}

# Logging
logging:
  level:
    org.springframework.cloud.config: DEBUG

# OAuth2 Configuration
oauth2:
  server-url: ${OAUTH2_SERVER_URL:http://localhost:9191}
  realm-url: ${oauth2.server-url}/realms/bookstore
