# Production Environment Configuration
spring:
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: validate

# Logging Configuration for Production
logging:
    level:
        root: WARN
        com.kiin: INFO
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file:
        name: /var/log/bookstore/${spring.application.name}.log

# Actuator Configuration for Production
management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics
    tracing:
        enabled: true
        sampling:
            probability: 0.1

# Security Configuration for Production
server:
    error:
        include-message: never
        include-stacktrace: never
