# Default configuration for all microservices
server:
  shutdown: graceful

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

# Common Eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

# Common Actuator configuration
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: true
  otlp:
    tracing:
      endpoint: http://tempo:4318/v1/traces
  endpoint:
    env:
      show-values: ALWAYS

# OAuth2 Configuration
oauth2:
  server-url: ${OAUTH2_SERVER_URL:http://localhost:9191}
  realm-url: ${oauth2.server-url}/realms/bookstore

# Common logging configuration
logging:
  level:
    root: INFO
    com.kiin: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
