# BookStore WebApp Configuration
server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: bookstore-webapp
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${REALM_URL}
      client:
        registration:
          bookstore-webapp:
            client-id: bookstore-webapp-id
            client-secret: TaVa6Vj5J3X8BS7lDZ2anuTueQWiGJqb
            authorization-grant-type: authorization_code
            scope: openid, profile
            redirect-uri: http://localhost:8080/login/oauth2/code/bookstore-webapp
        provider:
          bookstore-webapp:
            issuer-uri: ${REALM_URL}

# BookStore Application Configuration
bookstore:
  api-gateway-url: http://localhost:8989

# OAuth2 Configuration
OAUTH2_SERVER_URL: http://localhost:9191
REALM_URL: ${OAUTH2_SERVER_URL}/realms/bookstore

# Actuator Configuration
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0
