# Catalog Service Configuration
server:
  port: 8081

spring:
  application:
    name: catalog-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

# Catalog Service Specific Configuration
catalog:
  page-size: 10

# Override tracing for catalog service
management:
  tracing:
    enabled: false

# Swagger Configuration
swagger:
  api-gateway-url: http://localhost:8989/catalog
