# Catalog Service Configuration
server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: catalog-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update

# Catalog Service Specific Configuration
catalog:
  page-size: 10

# Actuator Configuration
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://tempo:9411

# Swagger Configuration
swagger:
  api-gateway-url: http://localhost:8989/catalog
