# Discovery Server (Eureka) Configuration
server:
  port: 8761

spring:
  application:
    name: discovery-server

# Eureka Server Configuration
eureka:
  instance:
    hostname: discovery-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000

# Override management for discovery server
management:
  endpoints:
    web:
      exposure:
        include: "*"